package code;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stu
 */
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class Doctor_Chat extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_Chat
     */
    public static ServerSocket ss;
     static Socket s;
     static String receive2="",send2="";
    static DataInputStream din;
    static DataOutputStream dout;
    public Doctor_Chat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textbox2 = new javax.swing.JTextField();
        doctor_send = new javax.swing.JButton();
        save = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg_area2.setColumns(20);
        msg_area2.setRows(5);
        jScrollPane1.setViewportView(msg_area2);

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor");

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel2.setText("Type here :");

        textbox2.setForeground(new java.awt.Color(51, 51, 51));
        textbox2.setToolTipText("");
        textbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox2ActionPerformed(evt);
            }
        });

        doctor_send.setBackground(new java.awt.Color(51, 153, 0));
        doctor_send.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        doctor_send.setText("Send");
        doctor_send.setToolTipText("");
        doctor_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor_sendActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        save.setText("Save Chat");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textbox2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctor_send))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctor_send))
                .addGap(18, 18, 18)
                .addComponent(save)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox2ActionPerformed
 //        String receiver = doctor_text.getText();

            receive2=textbox2.getText();
    }//GEN-LAST:event_textbox2ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String doc_chat=msg_area2.getText();
        
        try
        {
            BufferedWriter writer = new BufferedWriter(new FileWriter("./PatientChat_Record.txt"));
            writer.write(doc_chat);
            writer.close();
           
        }
        catch (Exception e) {}
         JOptionPane.showMessageDialog(this,"Saved Successfully.");
         
        String f1;                   //for Student Chat table
        f1=this.msg_area2.getText();

     try{  
Class.forName("com.mysql.jdbc.Driver");  
//here sonoo is database name, root is username and password
    try (
            Connection con = DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/chatroom_db","root","")) {
        //here sonoo is database name, root is username and password
        int id=1;
        Statement stmt=con.createStatement();
//        stmt.executeUpdate("INSERT into patient VALUES ('2', 'ahmed','1234567')");
        ResultSet rs=stmt.executeQuery("select * from patient");
        
        while(rs.next()){
//            System.out.println(rs.getString(1)+"  "+rs.getString(2)+"  "+rs.getString(3));
        } 
      PreparedStatement ps=con.prepareStatement("INSERT into doc_chat VALUES (?)");
      
      ps.setString(1, f1);
      
      ps.executeUpdate();
//      JOptionPane.showMessageDialog(rootPane, "Reiistration Successfull");
      
    }
}catch(Exception e){ System.out.println(e);} 
         
    
        
    }//GEN-LAST:event_saveActionPerformed

    private void doctor_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_sendActionPerformed
      
// TODO add your handling code here:
             try{
        String msgout ="";
        msgout = textbox2.getText().trim();
        dout.writeUTF(msgout);
        
    }
    catch(Exception e){
        System.out.println("Exception occured!!");
    }
             
        


    }//GEN-LAST:event_doctor_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Chat().setVisible(true);
            }
        });
        
         String msgin = "",
                msgout="";
        try {
            ss = new ServerSocket(1201);
            s = ss.accept();

            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());
            while (!msgin.equals("exit")) {
                msgin = din.readUTF();
                receive2 = msgin;
                msg_area2.setText(msg_area2.getText().trim() + "\nPatient said:\t" + receive2+"\t");
               
            }

        } 
        catch (Exception e) {
            System.out.println("Exception occured!!");
        }
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doctor_send;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg_area2;
    private javax.swing.JButton save;
    private javax.swing.JTextField textbox2;
    // End of variables declaration//GEN-END:variables
}
